services:
  mariadb:
    image: zmutclik/mariadb:latest
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_APPUSER}
      MARIADB_PASSWORD: ${DB_APPPASS}
    ports:
      - "${DATA_PORT}:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      net:
    dns:
      - ${DNS1}
      - ${DNS2}

networks:
  net:

volumes:
  data:
#    driver_opts:
#      type: nfs
#      o: addr=${NFS_ADDRESS},nfsvers=4
#      device: ${NFS_PATH}
