CREATE USER 'user_backup'@'localhost' IDENTIFIED BY 'PASSYBACKUPX';
GRANT SELECT, LOCK TABLES, SHOW VIEW, EVENT, TRIGGER, RELOAD, PROCESS, SUPER, REPLICATION CLIENT ON *.* TO 'user_backup'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;